/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddProjectDto
 */
export interface AddProjectDto {
    /**
     * 
     * @type {string}
     * @memberof AddProjectDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddProjectDto
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddProjectDto
     */
    clientId?: string | null;
}

/**
 * Check if a given object implements the AddProjectDto interface.
 */
export function instanceOfAddProjectDto(value: object): value is AddProjectDto {
    return true;
}

export function AddProjectDtoFromJSON(json: any): AddProjectDto {
    return AddProjectDtoFromJSONTyped(json, false);
}

export function AddProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddProjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
    };
}

export function AddProjectDtoToJSON(json: any): AddProjectDto {
    return AddProjectDtoToJSONTyped(json, false);
}

export function AddProjectDtoToJSONTyped(value?: AddProjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'clientId': value['clientId'],
    };
}

