/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddSectionDto
 */
export interface AddSectionDto {
    /**
     * 
     * @type {string}
     * @memberof AddSectionDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddSectionDto
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddSectionDto
     */
    projectId?: string;
}

/**
 * Check if a given object implements the AddSectionDto interface.
 */
export function instanceOfAddSectionDto(value: object): value is AddSectionDto {
    return true;
}

export function AddSectionDtoFromJSON(json: any): AddSectionDto {
    return AddSectionDtoFromJSONTyped(json, false);
}

export function AddSectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function AddSectionDtoToJSON(json: any): AddSectionDto {
    return AddSectionDtoToJSONTyped(json, false);
}

export function AddSectionDtoToJSONTyped(value?: AddSectionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'projectId': value['projectId'],
    };
}

