/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTodoDto
 */
export interface AddTodoDto {
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    dueAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    projectId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    sectionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    priorityId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddTodoDto
     */
    statusId?: string | null;
}

/**
 * Check if a given object implements the AddTodoDto interface.
 */
export function instanceOfAddTodoDto(value: object): value is AddTodoDto {
    return true;
}

export function AddTodoDtoFromJSON(json: any): AddTodoDto {
    return AddTodoDtoFromJSONTyped(json, false);
}

export function AddTodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTodoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'] == null ? undefined : json['summary'],
        'description': json['description'] == null ? undefined : json['description'],
        'dueAt': json['dueAt'] == null ? undefined : json['dueAt'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'sectionId': json['sectionId'] == null ? undefined : json['sectionId'],
        'priorityId': json['priorityId'] == null ? undefined : json['priorityId'],
        'statusId': json['statusId'] == null ? undefined : json['statusId'],
    };
}

export function AddTodoDtoToJSON(json: any): AddTodoDto {
    return AddTodoDtoToJSONTyped(json, false);
}

export function AddTodoDtoToJSONTyped(value?: AddTodoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
        'description': value['description'],
        'dueAt': value['dueAt'],
        'projectId': value['projectId'],
        'sectionId': value['sectionId'],
        'priorityId': value['priorityId'],
        'statusId': value['statusId'],
    };
}

