/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoggedUserModel
 */
export interface LoggedUserModel {
    /**
     * 
     * @type {string}
     * @memberof LoggedUserModel
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LoggedUserModel
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserModel
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LoggedUserModel
     */
    isAuthenticated?: boolean;
}

/**
 * Check if a given object implements the LoggedUserModel interface.
 */
export function instanceOfLoggedUserModel(value: object): value is LoggedUserModel {
    return true;
}

export function LoggedUserModelFromJSON(json: any): LoggedUserModel {
    return LoggedUserModelFromJSONTyped(json, false);
}

export function LoggedUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoggedUserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
        'name': json['name'] == null ? undefined : json['name'],
        'isAuthenticated': json['isAuthenticated'] == null ? undefined : json['isAuthenticated'],
    };
}

export function LoggedUserModelToJSON(json: any): LoggedUserModel {
    return LoggedUserModelToJSONTyped(json, false);
}

export function LoggedUserModelToJSONTyped(value?: LoggedUserModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'isAdmin': value['isAdmin'],
        'name': value['name'],
        'isAuthenticated': value['isAuthenticated'],
    };
}

