/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginModel
 */
export interface LoginModel {
    /**
     * 
     * @type {string}
     * @memberof LoginModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginModel
     */
    password: string;
}

/**
 * Check if a given object implements the LoginModel interface.
 */
export function instanceOfLoginModel(value: object): value is LoginModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginModelFromJSON(json: any): LoginModel {
    return LoginModelFromJSONTyped(json, false);
}

export function LoginModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginModelToJSON(json: any): LoginModel {
    return LoginModelToJSONTyped(json, false);
}

export function LoginModelToJSONTyped(value?: LoginModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

