/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterModel
 */
export interface RegisterModel {
    /**
     * 
     * @type {string}
     * @memberof RegisterModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterModel
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterModel
     */
    displayName: string;
}

/**
 * Check if a given object implements the RegisterModel interface.
 */
export function instanceOfRegisterModel(value: object): value is RegisterModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function RegisterModelFromJSON(json: any): RegisterModel {
    return RegisterModelFromJSONTyped(json, false);
}

export function RegisterModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'displayName': json['displayName'],
    };
}

export function RegisterModelToJSON(json: any): RegisterModel {
    return RegisterModelToJSONTyped(json, false);
}

export function RegisterModelToJSONTyped(value?: RegisterModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'displayName': value['displayName'],
    };
}

