/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionDetailDto
 */
export interface SectionDetailDto {
    /**
     * 
     * @type {string}
     * @memberof SectionDetailDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionDetailDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SectionDetailDto
     */
    color?: string | null;
}

/**
 * Check if a given object implements the SectionDetailDto interface.
 */
export function instanceOfSectionDetailDto(value: object): value is SectionDetailDto {
    return true;
}

export function SectionDetailDtoFromJSON(json: any): SectionDetailDto {
    return SectionDetailDtoFromJSONTyped(json, false);
}

export function SectionDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function SectionDetailDtoToJSON(json: any): SectionDetailDto {
    return SectionDetailDtoToJSONTyped(json, false);
}

export function SectionDetailDtoToJSONTyped(value?: SectionDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

