/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoDetailDto
 */
export interface TodoDetailDto {
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    description?: string | null;
    /**
     * 
     * @type {object}
     * @memberof TodoDetailDto
     */
    dueAt?: object;
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    priorityColor?: string | null;
}

/**
 * Check if a given object implements the TodoDetailDto interface.
 */
export function instanceOfTodoDetailDto(value: object): value is TodoDetailDto {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function TodoDetailDtoFromJSON(json: any): TodoDetailDto {
    return TodoDetailDtoFromJSONTyped(json, false);
}

export function TodoDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'summary': json['summary'],
        'description': json['description'] == null ? undefined : json['description'],
        'dueAt': json['dueAt'] == null ? undefined : json['dueAt'],
        'priorityColor': json['priorityColor'] == null ? undefined : json['priorityColor'],
    };
}

export function TodoDetailDtoToJSON(json: any): TodoDetailDto {
    return TodoDetailDtoToJSONTyped(json, false);
}

export function TodoDetailDtoToJSONTyped(value?: TodoDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'summary': value['summary'],
        'description': value['description'],
        'dueAt': value['dueAt'],
        'priorityColor': value['priorityColor'],
    };
}

