/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSectionDto
 */
export interface UpdateSectionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateSectionDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateSectionDto
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateSectionDto
     */
    projectId?: string;
}

/**
 * Check if a given object implements the UpdateSectionDto interface.
 */
export function instanceOfUpdateSectionDto(value: object): value is UpdateSectionDto {
    return true;
}

export function UpdateSectionDtoFromJSON(json: any): UpdateSectionDto {
    return UpdateSectionDtoFromJSONTyped(json, false);
}

export function UpdateSectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function UpdateSectionDtoToJSON(json: any): UpdateSectionDto {
    return UpdateSectionDtoToJSONTyped(json, false);
}

export function UpdateSectionDtoToJSONTyped(value?: UpdateSectionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'projectId': value['projectId'],
    };
}

