/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectDto
 */
export interface UpdateProjectDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDto
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDto
     */
    clientId?: string | null;
}

/**
 * Check if a given object implements the UpdateProjectDto interface.
 */
export function instanceOfUpdateProjectDto(value: object): value is UpdateProjectDto {
    return true;
}

export function UpdateProjectDtoFromJSON(json: any): UpdateProjectDto {
    return UpdateProjectDtoFromJSONTyped(json, false);
}

export function UpdateProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
    };
}

export function UpdateProjectDtoToJSON(json: any): UpdateProjectDto {
    return UpdateProjectDtoToJSONTyped(json, false);
}

export function UpdateProjectDtoToJSONTyped(value?: UpdateProjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'clientId': value['clientId'],
    };
}

