/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddProjectDto,
  ProjectDetailDto,
  UpdateProjectDto,
} from '../models/index';
import {
    AddProjectDtoFromJSON,
    AddProjectDtoToJSON,
    ProjectDetailDtoFromJSON,
    ProjectDetailDtoToJSON,
    UpdateProjectDtoFromJSON,
    UpdateProjectDtoToJSON,
} from '../models/index';

export interface ApiProjectProjectIdDeleteRequest {
    id: string;
}

export interface ApiProjectProjectIdGetRequest {
    id: string;
}

export interface ApiProjectProjectIdPatchRequest {
    id: string;
    updateProjectDto?: UpdateProjectDto;
}

export interface ApiProjectProjectPostRequest {
    addProjectDto?: AddProjectDto;
}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI {

    /**
     */
    async apiProjectProjectGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectDetailDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/Project`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectDetailDtoFromJSON));
    }

    /**
     */
    async apiProjectProjectGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectDetailDto>> {
        const response = await this.apiProjectProjectGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProjectProjectIdDeleteRaw(requestParameters: ApiProjectProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/Project/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProjectProjectIdDelete(requestParameters: ApiProjectProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProjectProjectIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiProjectProjectIdGetRaw(requestParameters: ApiProjectProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/Project/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProjectProjectIdGet(requestParameters: ApiProjectProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetailDto> {
        const response = await this.apiProjectProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProjectProjectIdPatchRaw(requestParameters: ApiProjectProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/Project/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectDtoToJSON(requestParameters['updateProjectDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProjectProjectIdPatch(requestParameters: ApiProjectProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetailDto> {
        const response = await this.apiProjectProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProjectProjectPostRaw(requestParameters: ApiProjectProjectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetailDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/Project`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddProjectDtoToJSON(requestParameters['addProjectDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProjectProjectPost(requestParameters: ApiProjectProjectPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetailDto> {
        const response = await this.apiProjectProjectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
