/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddSectionDto,
  SectionDetailDto,
  UpdateSectionDto,
} from '../models/index';
import {
    AddSectionDtoFromJSON,
    AddSectionDtoToJSON,
    SectionDetailDtoFromJSON,
    SectionDetailDtoToJSON,
    UpdateSectionDtoFromJSON,
    UpdateSectionDtoToJSON,
} from '../models/index';

export interface ApiSectionSectionIdDeleteRequest {
    id: string;
}

export interface ApiSectionSectionIdGetRequest {
    id: string;
}

export interface ApiSectionSectionIdPatchRequest {
    id: string;
    updateSectionDto?: UpdateSectionDto;
}

export interface ApiSectionSectionPostRequest {
    addSectionDto?: AddSectionDto;
}

/**
 * 
 */
export class SectionApi extends runtime.BaseAPI {

    /**
     */
    async apiSectionSectionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SectionDetailDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/Section`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SectionDetailDtoFromJSON));
    }

    /**
     */
    async apiSectionSectionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SectionDetailDto>> {
        const response = await this.apiSectionSectionGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionSectionIdDeleteRaw(requestParameters: ApiSectionSectionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSectionSectionIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/Section/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiSectionSectionIdDelete(requestParameters: ApiSectionSectionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiSectionSectionIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiSectionSectionIdGetRaw(requestParameters: ApiSectionSectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SectionDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSectionSectionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/Section/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiSectionSectionIdGet(requestParameters: ApiSectionSectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SectionDetailDto> {
        const response = await this.apiSectionSectionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionSectionIdPatchRaw(requestParameters: ApiSectionSectionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SectionDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSectionSectionIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/Section/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSectionDtoToJSON(requestParameters['updateSectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiSectionSectionIdPatch(requestParameters: ApiSectionSectionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SectionDetailDto> {
        const response = await this.apiSectionSectionIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionSectionPostRaw(requestParameters: ApiSectionSectionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SectionDetailDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/Section`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddSectionDtoToJSON(requestParameters['addSectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiSectionSectionPost(requestParameters: ApiSectionSectionPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SectionDetailDto> {
        const response = await this.apiSectionSectionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
