/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddTodoDto,
  TodoDetailDto,
  UpdateTodoDto,
} from '../models/index';
import {
    AddTodoDtoFromJSON,
    AddTodoDtoToJSON,
    TodoDetailDtoFromJSON,
    TodoDetailDtoToJSON,
    UpdateTodoDtoFromJSON,
    UpdateTodoDtoToJSON,
} from '../models/index';

export interface ApiTodoTodoIdDeleteRequest {
    id: string;
}

export interface ApiTodoTodoIdGetRequest {
    id: string;
}

export interface ApiTodoTodoIdPatchRequest {
    id: string;
    updateTodoDto?: UpdateTodoDto;
}

export interface ApiTodoTodoPostRequest {
    addTodoDto?: AddTodoDto;
}

/**
 * 
 */
export class TodoApi extends runtime.BaseAPI {

    /**
     */
    async apiTodoTodoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoDetailDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/Todo`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoDetailDtoFromJSON));
    }

    /**
     */
    async apiTodoTodoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoDetailDto>> {
        const response = await this.apiTodoTodoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoTodoIdDeleteRaw(requestParameters: ApiTodoTodoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoTodoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/Todo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTodoTodoIdDelete(requestParameters: ApiTodoTodoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTodoTodoIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiTodoTodoIdGetRaw(requestParameters: ApiTodoTodoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoTodoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/Todo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoTodoIdGet(requestParameters: ApiTodoTodoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDetailDto> {
        const response = await this.apiTodoTodoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoTodoIdPatchRaw(requestParameters: ApiTodoTodoIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoTodoIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/Todo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTodoDtoToJSON(requestParameters['updateTodoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoTodoIdPatch(requestParameters: ApiTodoTodoIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDetailDto> {
        const response = await this.apiTodoTodoIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoTodoPostRaw(requestParameters: ApiTodoTodoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDetailDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/Todo`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddTodoDtoToJSON(requestParameters['addTodoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoTodoPost(requestParameters: ApiTodoTodoPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDetailDto> {
        const response = await this.apiTodoTodoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
